---
cloud_service_group: SQLServers
cloud_service_type: Server
name: Databases Count by Server
query:
  aggregate:
    - unwind:
        path: data.databases
    - group:
        keys:
          - name: name
            key: data.databases.server_name
        fields:
          - name: value
            key: data.databases.server_name
            operator: text
options:
  chart_type: COLUMN
