---
cloud_service_group: SQLServers
cloud_service_type: Server
name: SQLServers Total Count by Location
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            key: region_code
            operator: count
options:
  chart_type: COLUMN
