---
cloud_service_group: Snapshots
cloud_service_type: Instance
name: Snapshots Total Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.disk_size_gb
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
      source_unit: GB