---
cloud_service_group: Snapshots
cloud_service_type: Instance
name: Snapshots Total Count by Subscription
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: account
            operator: count
options:
  chart_type: DONUT
