---
cloud_service_group: Snapshots
cloud_service_type: Instance
name: Snapshot Total Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.disk_size_gb
            operator: sum
