---
cloud_service_group: ContainerInstances
cloud_service_type: Container
name: Total Memory Size
query:
  aggregate:
    - unwind:
        path: data.containers
    - group:
        fields:
          - name: value
            key: data.containers.resources.requests.memory_in_gb
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
      source_unit: GB
