---
cloud_service_group: ContainerInstances
cloud_service_type: Container
name: Total Gpu Count
query:
  aggregate:
    - unwind:
        path: data.containers
    - group:
        fields:
          - name: value
            key: data.containers.resources.requests.gpu.count
            operator: sum
options:
  value_options:
    key: value
    options:
      default: 0
