---
cloud_service_group: ContainerInstances
cloud_service_type: Container
name: Total Container Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.containers
            operator: sum
options:
  value_options:
    key: value
    options:
      default: 0
