---
cloud_service_group: VirtualNetworks
cloud_service_type: Instance
name: Count by Subscription
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
