---
cloud_service_group: VirtualNetworks
cloud_service_type: Instance
name: Subnet Count by Region
query:
  aggregate:
   - unwind:
       path: data.subnets
   - group:
       keys:
       - name: name
         key: region_code
       fields:
        - name: value
          key: region_code
          operator: count
options:
  chart_type: COLUMN
