---
cloud_service_group: VirtualMachines
cloud_service_type: Instance
name: Total Memory Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.hardware.memory
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
      source_unit: GB
