---
cloud_service_group: StorageAccounts
cloud_service_type: Instance
name: Total Blob Size
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.blob_size_display
            operator: sum
options:
  value_options:
    key: value
    type: size
    options:
      default: 0
