---
cloud_service_group: StorageAccounts
cloud_service_type: Instance
name: Blob Size by Resource Group
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.resource_group
        fields:
          - name: value
            key: data.blob_size_display
            operator: sum
options:
  chart_type: DONUT
  value_options:
    key: value
    type: size
