---
cloud_service_group: MySQLServers
cloud_service_type: Server
name: MySQLServers Total Count by Subscription
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: account
            operator: count
options:
  chart_type: DONUT
