---
cloud_service_group: MySQLServers
cloud_service_type: Server
name: MySQLServers Total Count by Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            key: region_code
            operator: count
options:
  chart_type: COLUMN
