---
cloud_service_group: CosmosDB
cloud_service_type: Instance
name: Databases Total Count by Region
query:
  aggregate:
    - unwind:
        path: data.sql_databases
    - group:
        keys:
          - name: name
            key: data.name
        fields:
          - name: count
            key: data.sql_databases
            operator: count
options:
  chart_type: COLUMN
