---
cloud_service_group: VMScaleSets
cloud_service_type: ScaleSet
name: Total Count by Subscription
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
