---
cloud_service_group: VMScaleSets
cloud_service_type: ScaleSet
name: Instance Count
query:
  aggregate:
   - group:
       fields:
         - name: value
           key: data.instance_count
           operator: sum
