---
metric_id: metric-azure-network-sgs-instance
name: Instance Count
metric_type: GAUGE
resource_type: inventory.CloudService:azure.NetworkSecurityGroups.Instance
query_options:
  group_by:
    - key: region_code
      name: Region
      reference:
        resource_type: inventory.Region
        reference_key: region_code
    - key: data.tenant_id
      name: Tenant ID
    - key: data.subscription_name
      name: Subscription Name
    - key: account
      name: Subscription ID
    - key: data.resource_group
      name: Resource Group
      default: true
    - key: data.provisioning_state
      name: Provisioning State
      default: true
  fields:
    value:
      operator: count
unit: Count
namespace_id: ns-azure-network-sgs-instance
version: '1.0'