---
cloud_service_group: NetworkSecurityGroups
cloud_service_type: Instance
name: NetworkSecurityGroups Inbound Rule Total Count by Subscription
query:
  aggregate:
    - unwind:
        path: data.inbound_security_rules
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: data.inbound_security_rules
            operator: count
options:
  chart_type: DONUT
