---
cloud_service_group: PublicIPAddresses
cloud_service_type: IPAddress
name: PublicIPAddress Total Count by Location
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            key: region_code
            operator: count
options:
  chart_type: COLUMN
