---
cloud_service_group: PublicIPAddresses
cloud_service_type: IPAddress
name: PublicIPAddresses Total Count by Subscription
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: account
            operator: count
options:
  chart_type: DONUT
