---
cloud_service_group: PublicIPAddresses
cloud_service_type: IPAddress
name: PublicIPAddress Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: region_code
            operator: count
