---
cloud_service_group: ApplicationGateways
cloud_service_type: Instance
name: ApplicationGateways Total Count by Region
query:
  aggregate:
    - group:
        keys:
          - name: region_code
            key: region_code
        fields:
          - name: value
            key: region_code
            operator: count
options:
  chart_type: COLUMN
