---
cloud_service_group: PostgreSQLServers
cloud_service_type: Server
name: Inbound Count by Tier
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.user_visible_state
        fields:
          - name: value
            key: data.user_visible_state
            operator: count
options:
  chart_type: COLUMN
