---
cloud_service_group: PostgreSQLServers
cloud_service_type: Server
name: PostgreSQLServers Total Count by Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            key: region_code
            operator: count
options:
  chart_type: COLUMN
