---
cloud_service_group: KeyVaults
cloud_service_type: Instance
name: KeyVaults Total Count by Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            key: region_code
            operator: count
options:
  chart_type: COLUMN
