---
cloud_service_group: Disks
cloud_service_type: Disk
name: Size by Subscription
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: instance_size
            operator: sum
options:
  chart_type: COLUMN
  value_options:
    key: value
    type: size
    options:
      default: 0
