---
cloud_service_group: Disks
cloud_service_type: Disk
name: Size by Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            key: instance_size
            operator: sum
options:
  chart_type: COLUMN
  name_options:
    key: name
    reference:
      resource_type: inventory.Region
      reference_key: region_code
å