---
cloud_service_group: Disks
cloud_service_type: Disk
name: Disk Total Size by Region
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: region_code
        fields:
          - name: value
            key: instance_size
            operator: sum
options:
  chart_type: COLUMN
