---
cloud_service_group: Disks
cloud_service_type: Disk
name: Size by Type
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: instance_type
        fields:
          - name: value
            key: instance_size
            operator: sum
options:
  chart_type: TREEMAP
