---
cloud_service_group: Disks
cloud_service_type: Disk
name: Disk Total Count per Resource Group
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: data.resource_group
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT
