---
cloud_service_group: Compute
cloud_service_type: Disk
name: Disk Total Size per Type
query:
  aggregate:
    - group:
        keys:
          - name: type
            key: instance_type
        fields:
          - name: size
            key: instance_size
            operator: sum
options:
  chart_type: TREEMAP
