---
cloud_service_group: Compute
cloud_service_type: Disk
name: Disk Total Size per Status
query:
  aggregate:
    - group:
        keys:
          - name: state
            key: data.disk_state
        fields:
          - name: size
            key: instance_size
            operator: sum
options:
  chart_type: DONUT
