---
cloud_service_group: WebPubSubService
cloud_service_type: Hub
name: Total EventHandler Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            key: data.web_pubsub_hub_evnet_handler_count_display
            operator: sum
options:
  value_options:
    key: value
    options:
      default: 0