---
cloud_service_group: WebPubSubService
cloud_service_type: Service
name: Count by Account
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            key: account
            operator: count
options:
  chart_type: DONUT
